### ISSUE TITLE
rezka changed voidboost

### ISSUE THREAD

**Issue by 10kkm** [NIKDISSV-Forever/HDRezka#5]
https://phaeton.stream.voidboost.cc/285a35dc73028c6c42c7134e48fbce9f:2024011321:NGVZZnZrZVZhTXNPd0VaQlZPMlE0cUNEdmdqWnRETWdrdFFqNm15ZnZMalBYSGFFNGJrcU5hdmtGYUluMGxJOWxmekVROVRxVEN5NWdodzhiUkhFQVE9PQ==/6/7/8/3/0/9/t58cy.mp4:hls:seg-2-v1-a1.ts

phaeton can be changed to other words

**Comment by ndenissov** [comment]
Changing these links doesn't affect the functionality of the package in any way, I didn't quite understand what you want?

**Comment by 10kkm** [comment]
It doesnt give correct links to download. When i try to open them it gives error that not found.

**Comment by ndenissov** [comment]
but does the video load normally on the site? And to solve this, are you saying to replace voidboost links?

**Comment by 10kkm** [comment]
On website i see 301 to link without prefix, then see links that have phaeton and etc, and they r different of ones from script

**Comment by ndenissov** [comment]
I see, it will be fixed soon.

**Comment by ndenissov** [comment]
```python
import hdrezka
async def main():
    player: hdrezka.PlayerMovie = await hdrezka.Player('https://rezka.ag/films/drama/1027-terminal-2004.html')
    stream = await player.get_stream()
    best = await stream.video.last_url # the original stream.video.last_url hasn't been edited, a new VideoURL has been returned
    worst = await stream.video[stream.video.min].last_url
    print(best)
    print(worst.mp4)
```
Just add `await` for each url.
