### ISSUE TITLE
Script receives 500 Server Error on fn long_url

### ISSUE THREAD

**Issue by Gokujo** [NIKDISSV-Forever/HDRezka#6]
`.venv/Lib/site-packages/hdrezka/post/post.py:18`
Just commented this line and 200 answer received from rezka

I am using Python 3.9 on Win 11

**Comment by Gokujo** [comment]
No problem on python 3.11

**Comment by ndenissov** [comment]
I recommend updating python to version >=3.10 and installing the latest version of the package.

---
### If there is no such possibility:

The hdrezka API has undergone some changes, but you can manually make changes to version 1.1.1 (the latest version supporting python 3.9) if necessary.
In the `hdrezka/post/urls.py` file:

Line 12:
```python
_match_quality_int = re.compile(r'(\d+)[pi]\s*($|\w+)').match
```

Replace with:

```python
_match_quality_int = re.compile(r'(\d+)([piK])\s*($|\w+)').match
```
see [this update](https://github.com/NIKDISSV-Forever/HDRezka/commit/249c053708b17aae85a8343fa6faa05941dc1af7#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4edR6).

Function Content

```python
def short_url(url: str) -> str:
```
and

```python
def long_url(url: str) -> str:
```
Replace with:

```python
    return url
```

see https://github.com/NIKDISSV-Forever/HDRezka/issues/4

And (line 46)

```python
        _i, self.addon = _i.groups()
```

Replace with:
```python
        _i, u, self.addon = _i.groups()
        if u == 'K':
            _i += '000'

```
Note https://github.com/NIKDISSV-Forever/HDRezka/issues/5: if what you are going to play the video through does not support redirection, you will need to manually process the 301/302 codes
